apiVersion: v1
kind: Namespace
metadata:
  name: mfcp-system
---
apiVersion: storage.k8s.io/v1
kind: CSIDriver
metadata:
  labels:
    addonmanager.kubernetes.io/mode: Reconcile
    k8s-app: meta-fuse-csi-plugin
  name: meta-fuse-csi-plugin.csi.storage.pfn.io
spec:
  attachRequired: false
  fsGroupPolicy: ReadWriteOnceWithFSType
  podInfoOnMount: true
  requiresRepublish: true
  storageCapacity: false
  volumeLifecycleModes:
  - Ephemeral

