name: ci
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - '*'
jobs:
  check:
    strategy:
      matrix:
        go-version:
          - 1.21.x
        os:
          - ubuntu

    name: build (${{ matrix.os }}/go-${{ matrix.go-version }})
    runs-on: ${{ matrix.os }}-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}

    - run: |
        make bootstrap
        make check

  test:
    strategy:
      matrix:
        go-version:
          - 1.21.x
        os:
          - ubuntu

    name: test (${{ matrix.os }}/go-${{ matrix.go-version }})
    runs-on: ${{ matrix.os }}-latest
    services:
      minio:
        image: ${{ (matrix.os == 'ubuntu') && 'bitnami/minio:2023.7.18' || ''}}
        ports:
          - 45677:9000
        options: >-
          --health-cmd "curl -I http://localhost:9000/minio/health/live -s"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        env:
          MINIO_ROOT_USER: minioadmin
          MINIO_ROOT_PASSWORD: minioadmin
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}
    - uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: temurin

    - run: make test
      env:
        TEST_ENDPOINT_URL: ${{ (matrix.os == 'ubuntu') && 'http://localhost:45677' || '' }}
